# Para gerar o site estático: mkdocs build
# Para rodar um servidor para testes: mkdocs serve

site_name: Helios - Sistema de votação eletrônica
site_description: 'Ajuda do sistema de votação eletrônica'
site_author: 'UFMT - Coordenação de Engenharia de Software'
copyright: 'Copyright &copy; 2020 - UFMT'
repo_url: http://www.ces.ufmt.br/CES/helios-server-ldap
repo_name: GOGs

nav:
    - Inicial: index.md
    - Eleitor - como votar: eleitor.md
    - Gestor - Como criar uma eleição: criar.md
    - Gestor - Como iniciar uma eleição: abrir.md
    - Gestor - Como finalizar uma eleição: fechar.md
    - Gestor - Estatísticas: estatisticas.md
    - Gestor - Como gerar chave do apurador: apurador-gerar.md
    - Apurador - Como usar chave do apurador: apurador-usar.md

theme:
  name: material
  include_sidebar: false
  language: pt
  logo: img/logo_vetor_fundo_branco_recortado.png
  favicon: img/favicon.png
  font:
    text: Raleway
  search:
    language: 'pt'
extra_css:
  - stylesheets/extra.css